var terrains = (function () {
    function t(description, beach, type) {
        return {
            description: description,
            beach: beach,
            type: type
        }
    }
    return [
        t("Grass 1", 2, "land"),
        t("Water, shallow", 2, "water"),
        t("Beach", 2, "land"),
        t("Dirt 3", 2, "land"),
        t("Shallows", 2, "water"),
        t("Leaves", 2, "land"),
        t("Dirt 1", 2, "land"),
        t("Farm", 2, "land"),
        t("Farm, dead", 2, "land"),
        t("Grass 3", 2, "land"),
        t("Forest", 2, "land"),
        t("Dirt 2", 2, "land"),
        t("Grass 2", 2, "land"),
        t("Palm forest", 2, "land"),
        t("Desert (sand)", 2, "land"),
        t("Water (shallow, not dockable)", 2, "water"),
        t("Grass 1 duplicate", 2, "land"),
        t("Jungle", 2, "land"),
        t("Bamboo", 2, "land"),
        t("Pine forest", 2, "land"),
        t("Oak forest", 2, "land"),
        t("Snow pine forest", 2, "land"),
        t("Water, deep", 2, "water"),
        t("Water, medium", 2, "water"),
        t("Road", 2, "land"),
        t("Road, broken", 2, "land"),
        t("Ice (ships can move)", 37, "water"),
        t("Building foundation", 2, "land"),
        t("Water (bridge; walkable, no ships)", 2, "land"),
        t("Farm, 0%", 2, "land"),
        t("Farm, 33%", 2, "land"),
        t("Farm, 66%", 2, "land"),
        t("Snow", 37, "land"),
        t("Snow dirt", 37, "land"),
        t("Snow grass", 37, "land"),
        t("Ice (no ships)", 37, "land"),
        t("Snow building foundation", 37, "land"),
        t("Ice beach", 37, "beach"),
        t("Road, snow", 37, "land"),
        t("Road, fungus", 2, "land"),
        t("Rock", 2, "land"),
        t("Savannah", 2, "land"),
        t("Dirt 4", 2, "land"),
        t("Road, desert", 2, "land"),
        t("Moorland", 2, "land"),
        t("Desert, cracked", 2, "land"),
        t("Quicksand", 2, "land"),
        t("Black", 2, "land"),
        t("Dragon forest", 2, "land"),
        t("Baobab forest", 2, "land"),
        t("Acacia forest", 2, "land"),
        t("Beach, white, vegetation", 51, "beach"),
        t("Beach, vegetation", 52, "beach"),
        t("Beach, white", 53, "beach"),
        t("Shallows, mangrove (buildable)", 53, "hybrid"),
        t("Mangrove forest", 53, "hybrid"),
        t("Leaves, jungle", 2, "land"),
        t("Water, deep ocean", 2, "water"),
        t("Water, azure", 2, "water"),
        t("Shallows, azure", 2, "water"),
        t("Grass, jungle", 2, "land"),
        t("Road, jungle", 2, "land"),
        t("Rainforest", 2, "land"),
        t("Rice farm", 2, "hybrid"),
        t("Rice farm, dead", 2, "hybrid"),
        t("Rice farm, 0%", 2, "hybrid"),
        t("Rice farm, 33%", 2, "hybrid"),
        t("Rice farm, 66%", 2, "hybrid"),
    ];
})();
    